"""Trade models for tracking buy/sell orders"""
from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, Enum as SQLEnum
from sqlalchemy.sql import func
from ..database import Base
import enum


class TradeType(enum.Enum):
    BUY = "BUY"
    SELL = "SELL"


class TradeStatus(enum.Enum):
    PENDING = "PENDING"
    FILLED = "FILLED"
    PARTIAL = "PARTIAL"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class SignalType(enum.Enum):
    STRONG_BUY = "STRONG_BUY"
    BUY = "BUY"
    HOLD = "HOLD"
    SELL = "SELL"
    STRONG_SELL = "STRONG_SELL"


class Trade(Base):
    """Individual trade/order records"""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)
    order_id = Column(String(100), nullable=True, unique=True, index=True)  # SSI order ID
    symbol = Column(String(20), nullable=False, index=True)
    trade_type = Column(SQLEnum(TradeType), nullable=False)
    quantity = Column(Integer, nullable=False)
    price = Column(Float, nullable=False)
    total_value = Column(Float, nullable=False)
    commission = Column(Float, nullable=False, default=0.0)
    status = Column(SQLEnum(TradeStatus), nullable=False, default=TradeStatus.PENDING)
    filled_quantity = Column(Integer, nullable=False, default=0)
    filled_price = Column(Float, nullable=True)
    reason = Column(String(500), nullable=True)  # Why this trade was made
    signal_id = Column(Integer, nullable=True)  # Link to trade signal
    executed_at = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    def __repr__(self):
        return f"<Trade {self.trade_type.value} {self.symbol}: {self.quantity} @ {self.price}>"


class TradeSignal(Base):
    """Trading signals generated by the strategy engine"""
    __tablename__ = "trade_signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, index=True)
    signal_type = Column(SQLEnum(SignalType), nullable=False)
    confidence = Column(Float, nullable=False)  # 0-1 confidence score
    price_at_signal = Column(Float, nullable=False)
    target_price = Column(Float, nullable=True)
    stop_loss_price = Column(Float, nullable=True)

    # Signal components
    technical_score = Column(Float, nullable=True)
    sentiment_score = Column(Float, nullable=True)
    fundamental_score = Column(Float, nullable=True)

    # Analysis summary
    analysis = Column(String(2000), nullable=True)

    # Whether signal was acted upon
    is_executed = Column(Boolean, nullable=False, default=False)
    trade_id = Column(Integer, nullable=True)  # Link to trade if executed

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    def __repr__(self):
        return f"<Signal {self.signal_type.value} {self.symbol}: conf={self.confidence:.2f}>"
